### ISSUE TITLE
文本两端对齐

### ISSUE THREAD

**Issue by myanbin** [myanbin/m#4]
```html
<div class="demo">
  <div>姓名</div>
  <div>手机号</div>
  <div>电子邮件</div>
</div>
```
```css
.demo {
  margin: 20px;
  padding: 5px;
}

.demo div {
  width: 80px;
/*   text-align:justify; */
/*   text-justify:distribute-all-lines; */
  text-align-last:justify;
}
```

![image](https://user-images.githubusercontent.com/2127462/31535661-791d1820-b02e-11e7-9bde-6521be7e9e10.png)
